DEW-Twitter/config/routes.rb
DEWTwitter::Application.routes.draw do
  resources :tweets
  match "user" => "tweets#read_message"
  match "update" => "tweets#update_status"

end

DEW-Twitter/app/models/tweet.rb
class Tweet < ActiveRecord::Base

Twitter.configure do |config|
  config.consumer_key = 'pToks66RC32cevL0QOdKBw' 
  config.consumer_secret = 'TvS5TwBprhBaoNrH4loUNnLSnHEivE1xUZMa9Oebe4'
  config.oauth_token = '313482608-4uofrTHoKIv9ebIs5aHX5ZCntDDaQMqkOB5LIQT1'
  config.oauth_token_secret = 'n3xvumJVRKr7p8HxRaWvbJcpQRwPrVmudGg2MQA3NA'
end

  def read_message 
  	return "sin user" if self.user.blank?
  	Twitter.user_timeline(self.user).first.text
  end

  def update_status
  	return "sin update" if self.message.blank?
  	Twitter.update(self.message)
  end

end

DEW-Twitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

DEW-Twitter/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def read_message
     @tweet = Tweet.new(params[:tweet])
     respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  def update_status
     @tweet = Tweet.new(params[:tweet])
     respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end


  def index
    @tweet = Tweet.new
    @tweets = Tweet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end
end

DEW-Twitter/app/helpers/application_helper.rb
module ApplicationHelper
end

DEW-Twitter/app/helpers/tweets_helper.rb
module TweetsHelper
end

DEW-Twitter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DEWTwitter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

DEW-Twitter/app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

DEW-Twitter/app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

DEW-Twitter/app/views/tweets/index.html.erb
<h1>Listing tweets</h1>
<%= form_for(@tweet, :url => "user") do |f| %>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit "Buscar" %>
  </div>
<% end %>

<%= form_for(@tweet, :url => "update") do |f| %>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit "Enviar" %>
  </div>
<% end %>

DEW-Twitter/app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

DEW-Twitter/app/views/tweets/read_message.html.erb
<h1>Hola</h1>
<%= @tweet.read_message %>

DEW-Twitter/app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @tweet.message %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

DEW-Twitter/app/views/tweets/update_status.html.erb
<h1>Estado cambiado</h1>
<% @tweet.update_status %>
<%= @tweet.status %>